09-codice_sezione_DJANGO_LV_2/django_livello_due/django_livello_due/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls'))
]

09-codice_sezione_DJANGO_LV_2/django_livello_due/news/urls.py
from django.urls import path

from .views import ArticoloDetailViewCB, ArticoloListView, home #articoloDetailView,

urlpatterns = [
    path("", home, name="homeview"),
    # path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli")

]

09-codice_sezione_DJANGO_LV_2/django_livello_due/news/models.py
from django.db import models
from django.urls import reverse

# I modelli sono sottoclassi di django.db.models.Model
# I campi dei modelli sono invece definiti in django.db.models.fields
# Campi dei Modelli: https://docs.djangoproject.com/en/2.0/ref/models/fields/
# ForeignKey: https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ForeignKey
# Making Queries: https://docs.djangoproject.com/en/2.0/topics/db/queries/

# Create your models here.

class Giornalista(models.Model):
    """ il modello generico di un giornalista """
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome + " " + self.cognome

    class Meta:
        # link utile : https://docs.djangoproject.com/en/2.0/ref/models/options/
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"


class Articolo(models.Model):
    """ il modello generico di un articolo di news """
    titolo = models.CharField(max_length=100) # alcuni campi necessitano di parametri obbligatori!
    contenuto = models.TextField()
    giornalista = models.ForeignKey(Giornalista, 
                                    on_delete=models.CASCADE, 
                                    related_name="articoli")

    def __str__(self):
        return self.titolo

    def get_absolute_url(self):
        return reverse("articolo_detail", kwargs={"pk": self.pk})

    class Meta:
        # link utile : https://docs.djangoproject.com/en/2.0/ref/models/options/
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

09-codice_sezione_DJANGO_LV_2/django_livello_due/news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Articolo, Giornalista

# Create your views here.

# def home(request):
#     return HttpResponse("<h1>Homepage!</h1>")

# def home(request):
#     a = []
#     g = []
#     for art in Articolo.objects.all():
#         a.append(art.titolo)
#
#     for gio in Giornalista.objects.all():
#         g.append(gio.nome)
#
#     response = str(a) + "<br>" + str(g)
#     print(response)
#
#     return HttpResponse("<h1>" + response + "</h1>")

# def home(request):
#     a = ""
#     g = ""
#     for art in Articolo.objects.all():
#         a += (art.titolo + "<br>")
#
#     for gio in Giornalista.objects.all():
#         g += (gio.nome + "<br>")
#     response = "Articoli:<br>" + a + "<br>Giornalisti:<br>" + g
#
#     return HttpResponse("<h1>" + response + "</h1>")

def home(request):
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti": giornalisti}
    print(context)
    return render(request, "homepage.html", context)

# def articoloDetailView(request, pk):
#     # articolo = Articolo.objects.get(pk=pk)
#     articolo = get_object_or_404(Articolo, pk=pk)
#     context = {"articolo": articolo}
#     return render(request, "articolo_detail.html", context)


### GCBV Generic Class Based Views
# Documentazione Ufficiale: https://docs.djangoproject.com/en/2.0/ref/class-based-views/generic-display/

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

class ArticoloDetailViewCB(DetailView):
    model = Articolo
    template_name = "articolo_detail.html"


class ArticoloListView(ListView):
    model = Articolo
    template_name = "lista_articoli.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["articoli"] = Articolo.objects.all()
        return context

09-codice_sezione_DJANGO_LV_2/django_livello_due/templates/base.html
{% load static %}
<!doctype html>
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'news.css' %}">

    <title>{% block head_title %}Hello, world!{% endblock head_title %}</title>
  </head>
  <body>
      <h1>Questa frase sarà presente in ogni template!</h1>
    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

09-codice_sezione_DJANGO_LV_2/django_livello_due/templates/homepage.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} | homepage{% endblock head_title %}

{% block content %}

    <h1>Questa è la homepage del sito! </h1>
    <h2>Benvenuti alla funzione home!</h2>

    {{ articoli }}
    {{ giornalisti }}

    <br>
    <h4>Giornalisti:</h4>
    {% for giornalista in giornalisti %}
        <p>{{ giornalista.nome }} {{ giornalista.cognome }}</p>
    {% endfor %}

    <hr>
    <h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Titolo: </strong><a href="{{ articolo.get_absolute_url }}">{{ articolo.titolo }}</a></p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        <hr>
    {% endfor %}

    <br>
    <hr>

    <h4>Giornalisti:</h4>
    {% for giornalista in giornalisti %}
        <p>{{ giornalista.nome }} {{ giornalista.cognome }}</p>
        <p>Articoli:</p>
        {% for articolo in giornalista.articolo_set.all %}
            <p>{{ articolo.titolo }}</p>
        {% empty %}
            <p>{{ giornalista.nome }} non ha scritto alcun articolo!</p>
        {% endfor %}
        <hr>
    {% endfor %}

    <nav>
        <a href="https://docs.djangoproject.com/en/2.0/ref/models/options/#default-related-name">LINK RELAZIONE INVERSA</a>
        <a href="https://docs.djangoproject.com/en/2.0/topics/templates/">Link Templates</a>
        <a href="https://docs.djangoproject.com/en/2.0/ref/templates/language/">Django Template Language</a>
        <a href="https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#ref-templates-builtins-tags">Link Template Tag Reference</a>
    </nav>

{% endblock content %}